### ISSUE TITLE
Install has failed

### ISSUE THREAD

**Issue by keenam** [senlin/soblossom#20]
Hello!

I would like to ask for assistance, please. After cloning from Git and on executing `npm install && bower install && grunt build`, I get the following output:

```
npm WARN package.json soblossom@0.0.1 No repository field.
-
> node-sass@1.2.3 install /home/mycapp/webapps/htdocs_my_com_capp/wp-content/themes/soblossom/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/mycapp/webapps/htdocs_my_com_capp/wp-content/themes/soblossom/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@1.2.3 postinstall /home/mycapp/webapps/htdocs_my_com_capp/wp-content/themes/soblossom/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /home/mycapp/webapps/htdocs_my_com_capp/wp-content/themes/soblossom/node_modules/node-sass/vendor/linux-x64/binding.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mycapp/webapps/htdocs_my_com_capp/wp-content/themes/soblossom/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Linux 2.6.32-431.23.3.el6.x86_64
npm ERR! argv "/home/mycapp/bin/node" "/home/mycapp/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mycapp/webapps/htdocs_my_com_capp/wp-content/themes/soblossom/npm-debug.log
```

What do I need to do, to go further from here?

Thank you!

**Comment by senlin** [comment]
Apologies for the late response, I thought I should get notifications automatically fro my own repositories.

Since April 14 we have update the repo a couple of times, do you still run into this issue?
